### ISSUE TITLE
When projects\_index.md title is in Chinese,Firefox and IE can't jump to the right way

### ISSUE THREAD

**Issue by Phoenix-Ann** [victoriadotdev/hugo-theme-introduction#112]
Browser compatibility
Step:
1.Set projects\_index.md or Blog\_index.md title in Chinese,as blow
`title: "句读" `
2.Click the navbar-item ”句读“ with Firefox or IE
![image](https://user-images.githubusercontent.com/17487620/49214921-9d3e0700-f402-11e8-8401-f26e050156d7.png)
3.Can't jump to the right way.

PS：When Click the navbar-item ”句读“ with Chrome,it works well.

**Comment by snow2k9** [comment]
Hey, just tried to reproduce, `content/zh/projects/_index.md`
```
---
title: "项目"
---
```
Scrolled to my Projects, as expected
On Linux Firefox 64.0 (64-Bit) and Windows Firefox 64.0.2 (64-Bit) and latest commit of introduction

**Comment by hanzei** [comment]
Hey @Phoenix-Ann,

Would you please try to repo this issue with the latest `master`?

**Comment by Phoenix-Ann** [comment]
The latest version works

> Hey @Phoenix-Ann,
> 
> Would you please try to repo this issue with the latest `master`?

The latest version works
