### ISSUE TITLE
Also get the project open in "pop-up" when using self defined menu.

### ISSUE THREAD

**Issue by batch22** [victoriadotdev/hugo-theme-introduction#132]
I'm trying out this wonderful theme.

I love that in the example site that when you click on a project that it opens as a pop-up or overlay.
But actually when I'm using my self defined menu with a separate page for "Projects" I don't seem to get the popup. 
So i.e. when on site localhost:1313/projects/ the projects are listed but when I click a project it doesn't open as a overlay pop-up. Instead it opens as a separate page as well http://localhost:1313/projects/photography/

Can someone help me out to adjust some code so that on http://localhost:1313/projects/ the projects can also appear as popups?

Cheers!

**Comment by hanzei** [comment]
Hey @batch22,

Glad you like the theme. Does your site by any change has more projects then three?

Could you please try and comment out `params.home.numberOfProjectsToShow` in `config.toml`?

**Comment by batch22** [comment]
Hello @hanzei,

Thanks for you reply. 

I did try your suggestion to comment out the line but there is no difference.
The site still has the basic content with 3 projects. In future I would love to populate to more projects.

Since it's a separate page popup would be awesome so vistors could just click to close the popup and remain in projects overview page so they won't have to browse 'back'.

**Comment by hanzei** [comment]
Did you alter `exampleSite` in any way? If so, mind sharing this code?

**Comment by batch22** [comment]
No I didn't alter it. I just tested it with a new site with clean introduction theme.
created custom menu with separate /projects/ page and there it also happens not to pop-up.

**Comment by hanzei** [comment]
Could you provide some easy to follow steps on how to reproduce this exactly?

**Comment by batch22** [comment]
Yes sure...

-You can quickly see reproduce it when you make new site in HUGO.
-Add clean introduction theme to themes folder.
- and alter the example site, config.toml. then you can easily see it.
Here's the adjustment in the toml.
` #If you don't want to use the default menu, you can define one by yourself
 [[menu.main]]
     name    = "Home"
     url     = "/"
     weight  = 0
 [[menu.main]]
     name    = "projects"
     url     = "/projects/"
     weight  = 1`

**Comment by batch22** [comment]
After editing the toml you can cd to exampleSite dir: 
hugo serve  --themesDir ../..
Then you can see so no popups are being used when using self defined menu

**Comment by hanzei** [comment]
I'm still not able to repo this issue. Would you be open to share your site's code?

**Comment by batch22** [comment]
I appreciate your help but  I already skipped this project on Hugo. 

When you test it by altering as mentioned above you could easily replicate the issue. 

Cheers!
