### ISSUE TITLE
Missing Assets and CORS errors in theme's demos

### ISSUE THREAD

**Issue by onedrawingperday** [victoriadotdev/hugo-theme-introduction#135]
Hello again,

As you may remember, I am one of the maintainers of Hugo Themes and it has come to my attention that since PR #126 was merged this theme's demos both on the Hugo Themes website and on Netlify are throwing CORS errors. 

The CSS stylesheets are not loading because the credentials flag was set to `'same-origin'` in the above PR. see https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_settings_attributes for more info.

Also note 

My advice would be to either revert the CORS changes from #126 or amend the CORS policy to allow for the external assets that this theme requires or move every external asset in this repository.

Please do look into this and let me know once you issue a fix.

Thank you.

cc: @hanzei @victoriadotdev @digitalcraftsman

**Comment by victoriadotdev** [comment]
@onedrawingperday CORS policy has been amended plus some relative link tweaks. Netlify seems to work now, please let me know if the theme demo issue persists.

**Comment by onedrawingperday** [comment]
@victoriadotdev I will let you know in a separate issue, once I test your theme with the latest changes.
