### ISSUE TITLE
Menu doesn't respect weigth parameter

### ISSUE THREAD

**Issue by hanzei** [victoriadotdev/hugo-theme-introduction#149]
Another thing I came across is: The menu points at the top of the page now do not represent the weighted order of the sections. Which seems a bit odd to me. I would expect they appear from top to bottom like they appear from left to right in the menu bar.

_Originally posted by @timpauli in https://github.com/victoriadotdev/hugo-theme-introduction/pull/143#issuecomment-481880667_

**Comment by hanzei** [comment]
@snow2k9 Are you interested in fixing this?

**Comment by snow2k9** [comment]
Yep see #150
